### PR TITLE
Added animation for displaying social links of board members

### PR DESCRIPTION
**Pull request by ArpitKotecha**
Try hovering over a board member picture.

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 

Ask @yasho4 , she can help you in getting **social media usernames** of board members.

**Comment by ArpitKotecha** [comment]
Messaged all the board members will add them as soon I get links of all the board members

**Comment by vinitshahdeo** [comment]
@ArpitKotecha  Why Neelesh and Souvik didn't send you the links?

**Comment by ArpitKotecha** [comment]
Don't Know

**Comment by vinitshahdeo** [comment]
> Don't Know

Tell @ShreyaAnand, she'll ask them to send.

**Comment by ArpitKotecha** [comment]
> > Don't Know
> 
> Tell @ShreyaAnand, she'll ask them to send.

Told @yasho4 didi

**Comment by ArpitKotecha** [comment]
Added all links.

**Pull request merged**
