### PR TITLE
Kvssankar patch 1 removed button for dark theme

### PR DESCRIPTION
**Pull request by kvssankar**
Using DOM manipulation added dark theme to the website. Added SVG and Dark theme button in the top right corner of website.

### CODE REVIEW

**Comment by ArpitKotecha** [comment]
@kvssankar Try removing the button and just keep the icon (maybe put a small text below the animated icon) as the button is not looking good in mobile view.

**Comment by ArpitKotecha** [comment]
Also there seems to be a 404 error for mail-decode.min.js file. Although great work on dark mode.

**Comment by kvssankar** [comment]
> @kvssankar Try removing the button and just keep the icon (maybe put a small text below the animated icon) as the button is not looking good in mobile view.

Removed button and added text and
moved anime.min.js to assets now there is no need of anime-master folder

**Comment by ArpitKotecha** [comment]
> > @kvssankar Try removing the button and just keep the icon (maybe put a small text below the animated icon) as the button is not looking good in mobile view.
> 
> Removed button and added text and
> moved anime.min.js to assets now there is no need of anime-master folder

Reduce the size of icon and text maybe make the icon 4-5vh instead of 60px

**Pull request merged**
